### ISSUE TITLE
Getting error message The remote server returned an error: (401) Unauthorized.

### ISSUE THREAD

**Issue by Rhoustonhbc** [ExLibrisGroup/SpineOMatic#17]
I can't figure out why I'm getting this message when I try to use SpineOMatic: The remote server returned an error: (401) Unauthorized.

**Comment by mgobat** [comment]
What happens when you place the content of the "Alma Access" tab in a web browser?  For example:

https://api-XX.hosted.exlibrisgroup.com/almaws/v1/items?view=label&item_barcode={item_barcode}&apikey={api_key}

Replace XX with the appropriate region for you (ap, eu, na, ca, cn), replace {item_barcode} with a valid barcode for one your items, and replace {api_key} with the value in the "API Key" field on the "Alma Access" tab in Spine-O-Matic.

Do you still get 401: Unauthorized?

**Comment by Rhoustonhbc** [comment]
I still get an error, here is what I see: 
![image](https://user-images.githubusercontent.com/25597181/102540482-f3bb2400-4063-11eb-83ff-fd0f258207e8.png)

**Comment by mgobat** [comment]
Please confirm at https://developers.exlibrisgroup.com/manage/keys/ that the API key you are using has access to the correct area (Bibs) and the correct environment (Sandbox or Production, depending on which you wish to use).

**Comment by Rhoustonhbc** [comment]
Yes, the API key has access to Bibs and Production.

**Comment by mgobat** [comment]
Hmmm....puzzling.  Maybe we should take this to email until we figure it out.  Please email me the URL, without the API key, that you used to test in the browser earlier.  

mark.gobat@exlibrisgroup.com

Thanks.

**Comment by mgobat** [comment]
Ensured gateway routing was set up correctly.  The issue wasn't specific to Spine-O-Matic.
