### ISSUE TITLE
XML error

### ISSUE THREAD

**Issue by lizbodian** [ExLibrisGroup/SpineOMatic#18]
When I try to set up Spine-O-Matic with the latest release, I get an XML error: ***** ERROR *****
Can't retrieve XML file.

Error message: The underlying connection was closed: An unexpected error occurred on a send.

Can anyone tell me how to fix this?

-Liz

**Comment by mgobat** [comment]
Hi Liz...

Tyr this test, please.

Construct a URL like this:

1. From the "Alma Access" tab in Spine-O-Matic, copy the "ALMA URL" field contents.
2. Copy the "Method" field contents after the the text in step 1.
3. Replace {item_barcode} with a real item barcode in Alma.
4. Add "&apikey=" after the string in step 3.
5. Copy the "API Key" field contents after the string in step 4.

You should end up with something like:

https://api-eu.hosted.exlibrisgroup.com/almaws/v1/items?view=label&item_barcode=12345&apikey=somemessofcharacters

Then plug that entire string in a web browser to see if you get the same error.  This will help determine if the problem is Spine-O-Matic or your connection to Alma in general.

Good luck!

-mark
mark.gobat@exlibrisgroup.com

**Comment by lizbodian** [comment]
No error, and older versions of Spine-O-Matic that were already installed work just fine.  Is there a way to fix the connection to Spine-O-Matic?

-Liz

**Comment by mgobat** [comment]
Liz, was version 7.0 of Spine-O-Matic the last version that worked correctly for you?  Let's work on this off github.  I'm at mark.gobat@exlibrisgroup.com.  Thanks.

**Comment by mgobat** [comment]
User reported that it started working.

**Comment by Anjijade** [comment]
Curious if we get this message after building the URL as you outline does this mean our API is being blocked?
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<web_service_result>
<errorsExist>true</errorsExist>
<errorList>
<error>
<errorCode>UNAUTHORIZED</errorCode>
<errorMessage>
API-key not defined or not configured to allow this API.
</errorMessage>
</error>
</errorList>
</web_service_result>

**Comment by mgobat** [comment]
If you are getting the message "API-key not defined or not configured to allow this API.", please try recreating your API key and using the new one for SpineOMatic.

**Comment by sskaza** [comment]
Hi, 
We seem to be experiencing a similar error, except when we create the string after "This XML file does not appear to have any style information associated with it. The document tree is shown below," we are given the XML metadata of the material. Do you happen to know what this means or how we can restart our connection?
Thanks!

**Comment by mgobat** [comment]
@sskaza, which version of SpineOMatic are you using, and which particular error are you getting? There were two different errors mentioned earlier in the GitHub issue. If you are not running version 8.1.2, please upgrade. 
https://github.com/ExLibrisGroup/SpineOMatic/releases/download/v8.1.2/SpineLabeler.exe
