### ISSUE TITLE
Blank Labels (Dymo LabelWriter 450)

### ISSUE THREAD

**Issue by kustanovich** [ExLibrisGroup/SpineOMatic#33]
Greetings folks, 
 
I installed the latest version on my work PC. The API has been validated and the program seems to be communicating correctly with our DYMO LabelWriter 450 printer, which we used to use with Voayger (we’ll replace that printer next year, but I’m stuck with it for now). 

The problem is that the printer spits out blank labels when I use SpinoMatic, but it has no problem printing labels from the Dymo Connect software. The preview pane in SpinoMatic displays the call number correctly. So there’s some sort of miscommunication with Dymo and SpinoMatic. 
 
I found a workaround – copy the call number from the preview pane in SpinoMatic,  paste it into the blank square label in DymoConnect, and print it directly from there. The resulting label looks great… but all those time-wasting steps! :)
 
I tried to contact SpinoMatic at spinomatic-ggroup@bc.edu, but that email is no longer active. 
 
Does anyone have any idea what might be the problem? 
 
Thanks in advance. 
 
Alex
St. Francis College
Brooklyn, NY

**Comment by mgobat** [comment]
@kustanovich, do you have the ability to test with a different printer, perhaps a standard desktop or network printer, just to be sure SpineOMatic works without the specialty DYMO printer?  I know the labels won't be useable, but I'd like to be sure the issue is specific to the DYMO printer. Thanks.

**Comment by kustanovich** [comment]
Hi,

Thanks for such a prompt response. I just changed the printers and printed it out on my regular desktop printer.
The format is out of whack, obviously, but it printed without a problem.  So thank you for suggesting that.

The problem is not with the Dymo printer, however, because it prints out perfectly from the DymoConnect page.

Alex

**Comment by mgobat** [comment]
@kustanovich, thanks for performing that test. The results are as I expected, but wanted to confirm. Let me research this a bit. Thanks.

**Comment by kustanovich** [comment]
Thanks very much!

**Comment by mgobat** [comment]
@kustanovich, please ensure you have the latest Windows printer drivers installed for the printer.  See https://www.dymo.com/en_CA/labelwriter-450.html.

**Comment by mugwosim** [comment]
Hi there,
it seems, that we at Graz Medical University have pretty sure the same problem. We use a Citizen CL-E321 printer in a normal Win10-environment. The SpineOMatic utility itself (version 8.1.2) seems to do fine (data in preview is ok), but all the labels are completely empty. Printing from other programs works well!

Help highly appreciated!

Thx in advance,
Wolfgang

**Comment by kustanovich** [comment]
Hi Wolfgang,

I remedied the problem with a helpful suggestion from Tamara Marnell (see below).
I hope it works for you too.

Best,
Alex

On Sep 17, 2021, at 1:34 PM, Tamara Marnell ***@***.******@***.***>> wrote:
﻿Hi Alex,
 When I've had blank spine labels coming out of SpineOMatic, it was because of either large margins or an incorrect document size sent to the label printer. The text was getting shoved so far right or down that it came out blank.
 You can check the margin settings in the Print Setup tab and set them to 0 for testing, and also check the default paper size set in your preferences for the print driver (according to the internet, in Windows that's under Printers & scanners > your DYMO printer > Manage > Advanced).
 -Tamara

**Comment by mgobat** [comment]
@mugwosim, great detective work on the margins! Interestingly, I have replicated the problem but with the exact opposite results; using the dot for decimal works for me, but using comma results in the label being printed way over to the right. Changing my Windows regional setting to use the comma instead of the dot for the "Decimal symbols" results in using the dot and comma in SpineOMatic both printing the label correctly.

So that makes we wonder, what is your Windows regional setting for the decimal symbol, @mugwosim?

Windows: Control Panel -> Region -> Additional settings... -> Decimal symbol

**Comment by mugwosim** [comment]
Hi all,
in my regional settings the decimal symbol is the comma. When I change it to "dot" SpineOMatic works like expected with either decimals - thx for the hint! After resseting to comma the problem occurs again, differently to your system @mgobat , if I understood right...


Best regards,
Wolfgang
