### ISSUE TITLE
Call number parsing problem

### ISSUE THREAD

**Issue by R1ckyYg** [ExLibrisGroup/SpineOMatic#56]
We have tested printing the spine label by the holding call number (field = item_data.call_no), there is no problem in call number parsing.
![image](https://user-images.githubusercontent.com/118887177/210694444-862bb423-319e-4687-9a89-9e873dedd0c1.png)

However, the parsing failed if we changed to use item call number (field = item_data.alt_call_no).
![image](https://user-images.githubusercontent.com/118887177/210694561-abf66186-2c15-4022-b87b-93863f170dc3.png)

**Comment by R1ckyYg** [comment]
We expect the call number "HF1379" can be separated into two lines instead of showing in one line.

**Comment by mgobat** [comment]
@R1ckyYg, what are your "Call number" settings under "Other options" in the Template you are using?

**Comment by R1ckyYg** [comment]
@mgobat 
![image](https://user-images.githubusercontent.com/118887177/211233353-47147141-4af0-47f1-b18b-73f7353172d5.png)

**Comment by mgobat** [comment]
Thanks, @R1ckyYg.

**Comment by mgobat** [comment]
@R1ckyYg, what is your "Call Number Parsing Type" defined in Alma?  

https://knowledge.exlibrisgroup.com/Alma/Product_Documentation/010Alma_Online_Help_(English)/Physical_Resource_Management/070_Configuring_Resource_Management/060_Configuring_Call_Number_Parsing_when_Printing_Labels

**Comment by mgobat** [comment]
@R1ckyYg , I don't think this is a Cloud App problem. My test case has a call number of "KZ6385 .L37 2014" and an alt call number of "KZ6385 .L37345 2014".  My parsing routine for LC Call numbers is set to Parsing Routine 5 in Alma.. 

For the call number, the Cloud App gets the following from Alma:
call number passed to getCallNo = ["KZ","6385",".L37","2014"]

For the alt_call_no, the Cloud App gets the following from Alma:
call number passed to getCallNo = ["KZ6385",".L37345","2014"]

It appears that Alma isn't applying parsing routine 5 to the alt_call_no. I don't know if this is a defect in Alma or done by design. I will try to find out.

**Comment by R1ckyYg** [comment]
@mgobat 
![image](https://user-images.githubusercontent.com/118887177/211448850-597e860a-937d-4a11-9f90-4fbb070aee74.png)

**Comment by R1ckyYg** [comment]
@mgobat 
Do you have any solution that we can parse the alt call number "KZ6385 .L37345 2014" to ["KZ","6385",".L37345","2014"]?

**Comment by mgobat** [comment]
@R1ckyYg, this is apparently an issue outside the Cloud App. It might be a good idea to open a Support case. https://support.proquest.com/s/submit-a-case
