### ISSUE TITLE
Error:  Can't retrieve XML file

### ISSUE THREAD

**Issue by 1degreve** [ExLibrisGroup/SpineOMatic#65]
When the user scans a barcode, this message appears.

***** ERROR ***** 
Can't retrieve XML file.

Error message: The remote server returned an error: (500) Internal Server Error.

I checked for updates and updated to 8.1.2, but the error message remains.  Everything was working correctly last week.  This week the error message began appearing.

**Comment by mgobat** [comment]
@1degreve, this may be caused by several reasons. To try to get more details, please do the following:

1. Go the the "Alma Access" tab in SpineOMatic.
2. Copy the "ALMA URL" field to a text file.
3. Copy the "Method" field and paste it after the "ALMA URL" field in the text file.
4. Replace the string {item_barcode} with the real item barcode you are scanning.
5. After the barcode, type the string "apiKey=" in the text file.
6. Copy the "API Key" field after the "apiKey=" in the text file.
7. Copy the entire URL from the text file and paste it into your browser address bar, hit enter.
8. Please report back here the response you get.
